export * as NewService from './news'
export * as AnnouncementService from './announcements'
export * as LogoService from './logos'
export * as OurCompaniesService from './ourcompanies'
export * as CommunicationService from './communication'
export * as SliderService from './sliders'
